FROM developmentontheedge/ru.biosoft.uscience-base

# docker build -f Docker/Dockerfile.pilot -t developmentontheedge/ru.biosoft.uscience-pilot 

WORKDIR /root

ADD pom.xml /root
ADD src /root/src
ADD h2/pilot.mv.db.clean /root

# Build maven repository

RUN mvn exec:java -Dexec.mainClass=org.h2.tools.Shell -Dexec.args="-url 'jdbc:h2:mem:dummy' -user sa -sql 'SHOW TABLES'"

# Compile project

RUN mvn compile exec:java -Dexec.mainClass=ru.biosoft.uscience.bpmn.PilotMain


